In [4]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np


In [10]:
#### 2. Create a null vector of size 10 (★☆☆)
a = np.zeros((1, 10))  # Create an array of all zeros
print(a, "\n")
a.size

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 



10

In [24]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
b = np.zeros((1, 10)) 
b[0,4] = 1
print(b)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [34]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
c = np.arange(10,50)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [38]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
d = np.arange(0,9).reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [46]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

e = np.array([1,2,0,0,4,0])
print(e.nonzero())

(array([0, 1, 4]),)


In [58]:
#### 7. Create a 3x3 identity matrix (★☆☆)
d = np.arange(0,9).reshape(3,3)
np.eye(N=3, M=3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
f = np.random.random(9).reshape(3,3)
print(f)

[[0.85891473 0.16393677 0.96465117]
 [0.14705478 0.69957702 0.22313703]
 [0.78858327 0.14426774 0.36828376]]


In [88]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
g = np.random.random(100).reshape(10,10)
print(g.min())
print(g.max())

0.012355992728505183
0.9950629295382628


In [110]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
h = np.random.random(30)
h.mean()

np.float64(0.4646233596473264)

In [450]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
i = np.diag([1,2,3,4], k=-1)
print(i)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [124]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
j = np.random.random(25).reshape(5,5)
(j-j.mean())/j.std()

array([[ 1.2644843 , -1.28699752,  1.34602393, -1.09565816,  1.00005272],
       [-0.75048713,  0.1812426 , -0.91443034, -0.96815694,  0.53773535],
       [ 0.69215585, -0.80007684,  1.14241681,  0.09270145, -0.96068834],
       [ 1.31474521,  1.3361035 , -0.73977463,  1.1975525 , -1.29665555],
       [-0.25471179,  0.23786404,  1.08216406, -0.69421461, -1.66339048]])

In [128]:
#### 13. How to find common values between two arrays? (★☆☆)
array_1 = np.array([2,23,5,3,1,2,5,4,97])
array_2 = np.array([94,23,5,99,22,2,5,4,97])
np.intersect1d(array_1,array_2)

array([ 2,  4,  5, 23, 97])

In [136]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
k = np.random.random(10)
k_sorted = np.sort(k)
print(k)
print(k_sorted)

[0.98216108 0.8082641  0.5757299  0.06917915 0.12645824 0.86044953
 0.25379508 0.90385357 0.26162548 0.52258429]
[0.06917915 0.12645824 0.25379508 0.26162548 0.52258429 0.5757299
 0.8082641  0.86044953 0.90385357 0.98216108]


In [164]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
l = np.random.random(10)
print(l)
l[np.argmax(l)] = 0
print(l)

[0.75695055 0.39897412 0.19620275 0.49106913 0.12771644 0.16999281
 0.85723603 0.05036222 0.43543635 0.75242392]
[0.75695055 0.39897412 0.19620275 0.49106913 0.12771644 0.16999281
 0.         0.05036222 0.43543635 0.75242392]


In [218]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
np.random.seed(42)
m = np.arange(25).reshape(5,5)
print(m)
m_new = m - m.mean(axis=1,keepdims=True)
print(m_new)
print(m.mean(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]
[ 2.  7. 12. 17. 22.]


In [388]:
#### 17. How to get the n largest values of an array (★★★)
np.random.seed(42)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
Z[np.argsort(Z)][-n:]

array([9995, 9996, 9997, 9998, 9999])

In [402]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
np.random.seed(42)
p = np.arange(15).reshape(5,3)
print(p)
np.where(p < 5, p, np.square(p))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([[  0,   1,   2],
       [  3,   4,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]])